### ISSUE TITLE
Check functions

### ISSUE THREAD

**Issue by RitaGhilardi** [Rithoshi/Gold1#17]
I have now uploaded the final version of the tests, please verify whether every type of possible input is inserted in the tests.

**Comment by marcoovise** [comment]
I made some modification to the functions to control the type of the input of the tested functions. It should be unnecessary because argparse allow to specify the type of input, but in this way the functions are more robust than tests. Done in commit https://github.com/Rithoshi/Gold1/commit/98c876093e9091f10986148ab2833d25390bfc6c
